// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace NorthwindApp.Api.SDK.v1.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class BaseSupplier
    {
        /// <summary>
        /// Initializes a new instance of the BaseSupplier class.
        /// </summary>
        public BaseSupplier()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BaseSupplier class.
        /// </summary>
        public BaseSupplier(int? supplierId = default(int?), string companyName = default(string))
        {
            SupplierId = supplierId;
            CompanyName = companyName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "supplierId")]
        public int? SupplierId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "companyName")]
        public string CompanyName { get; set; }

    }
}
